"""Added devices, device_credentials, device_profiles

Revision ID: 279a75e1702d
Revises: d4867f3a4c0a
Create Date: 2022-09-28 09:18:35.696193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '279a75e1702d'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_profiles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('provision_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('default_rule_chain_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('default_dashboard_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('default_queue_name', sa.String(), nullable=True),
    sa.Column('provision_device_key', sa.String(), nullable=True),
    sa.Column('external_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provision_device_key')
    )
    op.create_table('devices',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('device_data', sa.JSON(), nullable=True),
    sa.Column('device_profile_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('external_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('firmware_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('software_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_profile_id'], ['device_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_devices_device_profile_id'), 'devices', ['device_profile_id'], unique=False)
    op.create_table('device_credentials',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('credentials_id', sa.String(), nullable=False),
    sa.Column('credentials_type', sa.String(), nullable=False),
    sa.Column('credentials_value', sa.String(), nullable=True),
    sa.Column('device_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_credentials_device_id'), 'device_credentials', ['device_id'], unique=False)
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_id', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_index(op.f('ix_device_credentials_device_id'), table_name='device_credentials')
    op.drop_table('device_credentials')
    op.drop_index(op.f('ix_devices_device_profile_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('device_profiles')
    # ### end Alembic commands ###
